
// <auto-generated>
//     此代码由工具生成。
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
//		如存在本生成代码外的新需求，请在相同命名空间下创建同名分部类实现 UserData1ConfigurationAppend 分部方法。
// </auto-generated>
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

using FluentJson.Configuration;
using FluentJson;
using XIMALAYACOPY.Core.Data.Decorator;
using XIMALAYACOPY.Core.Models.User;

namespace XIMALAYACOPY.Core.Data
{
    /// <summary>
    ///     UserData1
    /// </summary>
    /// <typeparam name="T"></typeparam>
    public partial class UserData1Decorator<T> : Decorator<T>
    {
        partial void doAddOtherConfig();
        /// <summary>
        ///     
        /// </summary>
        /// <typeparam name="result"></typeparam>
        public UserData1Decorator(Result<T> result)
            : base(result)
        {

        }
        /// <summary>
        ///     
        /// </summary>
        /// <typeparam name="result"></typeparam>
        public override void doAddConfig()
        {
            base.doAddConfig();
            this.Config.MapType<UserData>(map => map
                
                    .Field<System.String>(field => field.NickName, type => type.To("nickname"))

                    .Field<System.Boolean>(field => field.IsBeFollowed, type => type.To("be_followed"))

                    .Field<System.Int64>(field => field.CreateDate, type => type.To("create_time"))

                    .Field<System.Int64>(field => field.FollowerCount, type => type.To("followers_counts"))

                    .Field<System.Int64>(field => field.FollowingCount, type => type.To("followings_counts"))

                    .Field<System.String>(field => field.Gender, type => type.To("gender"))

                    .Field<System.Boolean>(field => field.IsVerified, type => type.To("isVerified"))

                    .Field<System.Boolean>(field => field.IsFollowed, type => type.To("is_follow"))

                    .Field<System.String>(field => field.MobileLargeLogo, type => type.To("logoPic"))

                    .Field<System.String>(field => field.MobileSmallLogo, type => type.To("smallPic"))

                    .Field<System.Int64>(field => field.TrackCount, type => type.To("tracks_counts"))

                    .Field<System.Int64>(field => field.Uid, type => type.To("uid"))

                    .Field<System.Int64>(field => field.LastUpdateDate, type => type.To("last_update"))

            );
            this.doAddOtherConfig();
        }
    }
}
