
// <auto-generated>
//     此代码由工具生成。
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
//		如存在本生成代码外的新需求，请在相同命名空间下创建同名分部类实现 SuperExploreIndexResultConfigurationAppend 分部方法。
// </auto-generated>
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

using FluentJson.Configuration;
using FluentJson;
using XIMALAYACOPY.Core.Data.Decorator;
using XIMALAYACOPY.Core.Models.Discover;

namespace XIMALAYACOPY.Core.Data
{
    /// <summary>
    ///     SuperExploreIndexResult
    /// </summary>
    /// <typeparam name="T"></typeparam>
    public partial class SuperExploreIndexResultDecorator<T> : Decorator<T>
    {
        partial void doAddOtherConfig();
        /// <summary>
        ///     
        /// </summary>
        /// <typeparam name="result"></typeparam>
        public SuperExploreIndexResultDecorator(Result<T> result)
            : base(result)
        {

        }
        /// <summary>
        ///     
        /// </summary>
        /// <typeparam name="result"></typeparam>
        public override void doAddConfig()
        {
            base.doAddConfig();
            this.Config.MapType<SuperExploreIndexResult>(map => map
                
                    .Field<System.Int32>(field => field.Ret, type => type.To("ret"))

                    .Field<System.String>(field => field.Message, type => type.To("msg"))

                    .Field<XIMALAYACOPY.Core.Models.FocusImage.FocusImageResult>(field => field.FocusImages, type => type.To("focusImages"))

                    .Field<XIMALAYACOPY.Core.Models.Category.CategoryResult>(field => field.Categories, type => type.To("categories"))

                    .Field<System.Object>(field => field.LatestActivity, type => type.To("latest_activity"))

                    .Field<System.Object>(field => field.LatestSpecial, type => type.To("latest_special"))

                    .Field<XIMALAYACOPY.Core.Models.Album.AlbumInfoResult1>(field => field.Albums, type => type.To("recommendAlbums"))

            );
            this.doAddOtherConfig();
        }
    }
}
