//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18444
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.Practices.Prism.MefExtensions.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.Practices.Prism.MefExtensions.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Bootstrapper sequence completed 的本地化字符串。
        /// </summary>
        internal static string BootstrapperSequenceCompleted {
            get {
                return ResourceManager.GetString("BootstrapperSequenceCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Configuring catalog for MEF 的本地化字符串。
        /// </summary>
        internal static string ConfiguringCatalogForMEF {
            get {
                return ResourceManager.GetString("ConfiguringCatalogForMEF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Configuring default region behaviors 的本地化字符串。
        /// </summary>
        internal static string ConfiguringDefaultRegionBehaviors {
            get {
                return ResourceManager.GetString("ConfiguringDefaultRegionBehaviors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Configuring MEF container 的本地化字符串。
        /// </summary>
        internal static string ConfiguringMefContainer {
            get {
                return ResourceManager.GetString("ConfiguringMefContainer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Configuring module catalog. 的本地化字符串。
        /// </summary>
        internal static string ConfiguringModuleCatalog {
            get {
                return ResourceManager.GetString("ConfiguringModuleCatalog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Configuring region adapters 的本地化字符串。
        /// </summary>
        internal static string ConfiguringRegionAdapters {
            get {
                return ResourceManager.GetString("ConfiguringRegionAdapters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Configuring ServiceLocator singleton 的本地化字符串。
        /// </summary>
        internal static string ConfiguringServiceLocatorSingleton {
            get {
                return ResourceManager.GetString("ConfiguringServiceLocatorSingleton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Creating catalog for MEF 的本地化字符串。
        /// </summary>
        internal static string CreatingCatalogForMEF {
            get {
                return ResourceManager.GetString("CreatingCatalogForMEF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Creating Mef container 的本地化字符串。
        /// </summary>
        internal static string CreatingMefContainer {
            get {
                return ResourceManager.GetString("CreatingMefContainer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Creating module catalog. 的本地化字符串。
        /// </summary>
        internal static string CreatingModuleCatalog {
            get {
                return ResourceManager.GetString("CreatingModuleCatalog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Creating shell 的本地化字符串。
        /// </summary>
        internal static string CreatingShell {
            get {
                return ResourceManager.GetString("CreatingShell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unable to locate the module with type &apos;{0}&apos; among the exported modules. Make sure the module name in the module catalog matches that specified on ModuleExportAttribute for the module type. 的本地化字符串。
        /// </summary>
        internal static string FailedToGetType {
            get {
                return ResourceManager.GetString("FailedToGetType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Initializing modules 的本地化字符串。
        /// </summary>
        internal static string InitializingModules {
            get {
                return ResourceManager.GetString("InitializingModules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Initializing shell 的本地化字符串。
        /// </summary>
        internal static string InitializingShell {
            get {
                return ResourceManager.GetString("InitializingShell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Logger was created successfully. 的本地化字符串。
        /// </summary>
        internal static string LoggerWasCreatedSuccessfully {
            get {
                return ResourceManager.GetString("LoggerWasCreatedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The CompositionContainer is required and cannot be null. 的本地化字符串。
        /// </summary>
        internal static string NullCompositionContainerException {
            get {
                return ResourceManager.GetString("NullCompositionContainerException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The ILoggerFacade is required and cannot be null. 的本地化字符串。
        /// </summary>
        internal static string NullLoggerFacadeException {
            get {
                return ResourceManager.GetString("NullLoggerFacadeException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The IModuleCatalog is required and cannot be null in order to initialize the modules. 的本地化字符串。
        /// </summary>
        internal static string NullModuleCatalogException {
            get {
                return ResourceManager.GetString("NullModuleCatalogException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Registering Framework Exception Types 的本地化字符串。
        /// </summary>
        internal static string RegisteringFrameworkExceptionTypes {
            get {
                return ResourceManager.GetString("RegisteringFrameworkExceptionTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Setting the RegionManager. 的本地化字符串。
        /// </summary>
        internal static string SettingTheRegionManager {
            get {
                return ResourceManager.GetString("SettingTheRegionManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Updating Regions. 的本地化字符串。
        /// </summary>
        internal static string UpdatingRegions {
            get {
                return ResourceManager.GetString("UpdatingRegions", resourceCulture);
            }
        }
    }
}
