
// <auto-generated>
//     此代码由工具生成。
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
//		如存在本生成代码外的新需求，请在相同命名空间下创建同名分部类实现 FocusImageDataConfigurationAppend 分部方法。
// </auto-generated>
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

using FluentJson.Configuration;
using FluentJson;
using XIMALAYACOPY.Core.Data.Decorator;
using XIMALAYACOPY.Core.Models.FocusImage;

namespace XIMALAYACOPY.Core.Data
{
    /// <summary>
    ///     FocusImageData
    /// </summary>
    /// <typeparam name="T"></typeparam>
    public partial class FocusImageDataDecorator<T> : Decorator<T>
    {
        partial void doAddOtherConfig();
        /// <summary>
        ///     
        /// </summary>
        /// <typeparam name="result"></typeparam>
        public FocusImageDataDecorator(Result<T> result)
            : base(result)
        {

        }
        /// <summary>
        ///     
        /// </summary>
        /// <typeparam name="result"></typeparam>
        public override void doAddConfig()
        {
            base.doAddConfig();
            this.Config.MapType<FocusImageData>(map => map
                
                    .Field<System.Int32>(field => field.ID, type => type.To("id"))

                    .Field<System.String>(field => field.ShortTitle, type => type.To("shortTitle"))

                    .Field<System.String>(field => field.TrackId, type => type.To("trackId"))

                    .Field<System.String>(field => field.LongTitle, type => type.To("longTitle"))

                    .Field<System.Int32>(field => field.Type, type => type.To("type"))

                    .Field<System.Int64>(field => field.Uid, type => type.To("uid"))

                    .Field<System.String>(field => field.Pic, type => type.To("pic"))

            );
            this.doAddOtherConfig();
        }
    }
}
