
// <auto-generated>
//     此代码由工具生成。
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
//		如存在本生成代码外的新需求，请在相同命名空间下创建同名分部类实现 AlbumData3ConfigurationAppend 分部方法。
// </auto-generated>
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

using FluentJson.Configuration;
using FluentJson;
using XIMALAYACOPY.Core.Data.Decorator;
using XIMALAYACOPY.Core.Models.Album;

namespace XIMALAYACOPY.Core.Data
{
    /// <summary>
    ///     AlbumData3
    /// </summary>
    /// <typeparam name="T"></typeparam>
    public partial class AlbumData3Decorator<T> : Decorator<T>
    {
        partial void doAddOtherConfig();
        /// <summary>
        ///     
        /// </summary>
        /// <typeparam name="result"></typeparam>
        public AlbumData3Decorator(Result<T> result)
            : base(result)
        {

        }
        /// <summary>
        ///     
        /// </summary>
        /// <typeparam name="result"></typeparam>
        public override void doAddConfig()
        {
            base.doAddConfig();
            this.Config.MapType<AlbumData>(map => map
                
                    .Field<System.Int64>(field => field.AlbumID, type => type.To("albumId"))

                    .Field<System.String>(field => field.AlbumCoverUrl140, type => type.To("coverLarge"))

                    .Field<System.String>(field => field.AlbumCoverUrl290, type => type.To("coverWebLarge"))

                    .Field<System.String>(field => field.AlbumCoverUrl640, type => type.To("coverOrigin"))

                    .Field<System.String>(field => field.AlbumCoverUrl86, type => type.To("coverSmall"))

                    .Field<System.String>(field => field.AvatarPath, type => type.To("avatarPath"))

                    .Field<System.Int64>(field => field.CategoryID, type => type.To("categoryId"))

                    .Field<System.Int64>(field => field.CreateDate, type => type.To("createdAt"))

                    .Field<System.String>(field => field.Intro, type => type.To("intro"))

                    .Field<System.Boolean>(field => field.IsVerified, type => type.To("isVerified"))

                    .Field<System.String>(field => field.NickName, type => type.To("nickname"))

                    .Field<System.Int64>(field => field.PlayCount, type => type.To("playTimes"))

                    .Field<System.String>(field => field.RichIntro, type => type.To("rich_intro"))

                    .Field<System.Int32>(field => field.Status, type => type.To("status"))

                    .Field<System.String>(field => field.Tags, type => type.To("tags"))

                    .Field<System.String>(field => field.Title, type => type.To("title"))

                    .Field<System.Int32>(field => field.TrackCount, type => type.To("tracks"))

                    .Field<System.Boolean>(field => field.IsFavorite, type => type.To("isFavorite"))

                    .Field<System.Int64>(field => field.Uid, type => type.To("uid"))

                    .Field<System.Int64>(field => field.UpdateDate, type => type.To("updatedAt"))

                    .Field<System.Int32>(field => field.SerialState, type => type.To("serializeStatus"))

                    .Field<System.Int64>(field => field.LastUptrackDate, type => type.To("lastUptrackAt"))

            );
            this.doAddOtherConfig();
        }
    }
}
