    
// <auto-generated>
//     此代码由工具生成。
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
//		如存在本生成代码外的新需求，请在相同命名空间下创建同名分部类实现 AlbumData1ConfigurationAppend 分部方法。
// </auto-generated>
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

using FluentJson.Configuration;
using FluentJson;
using XIMALAYACOPY.Core.Data.Decorator;
using XIMALAYACOPY.Core.Models.Album;

namespace XIMALAYACOPY.Core.Data
{
    /// <summary>
    ///     AlbumData1
    /// </summary>
    /// <typeparam name="T"></typeparam>
    public partial class AlbumData1Decorator<T> : Decorator<T>
    {
        partial void doAddOtherConfig();
        /// <summary>
        ///     
        /// </summary>
        /// <typeparam name="result"></typeparam>
        public AlbumData1Decorator(Result<T> result)
            : base(result)
        {

        }
        /// <summary>
        ///     
        /// </summary>
        /// <typeparam name="result"></typeparam>
        public override void doAddConfig()
        {
            base.doAddConfig();
            this.Config.MapType<AlbumData>(map => map
                
                    .Field<System.Int64>(field => field.AlbumID, type => type.To("id"))

                    .Field<System.String>(field => field.Title, type => type.To("title"))

                    .Field<System.String>(field => field.AlbumCoverUrl290, type => type.To("albumCoverUrl290"))

                    .Field<System.Int64>(field => field.PlayCount, type => type.To("playsCounts"))

                    .Field<System.Int64>(field => field.LastUptrackDate, type => type.To("lastUptrackAt"))

                    .Field<System.Int32>(field => field.SerialState, type => type.To("serialState"))

            );
            this.doAddOtherConfig();
        }
    }
}
