
// <auto-generated>
//     此代码由工具生成。
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
//		如存在本生成代码外的新需求，请在相同命名空间下创建同名分部类实现 AlbumData4ConfigurationAppend 分部方法。
// </auto-generated>
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

using FluentJson.Configuration;
using FluentJson;
using XIMALAYACOPY.Core.Data.Decorator;
using XIMALAYACOPY.Core.Models.Album;

namespace XIMALAYACOPY.Core.Data
{
    /// <summary>
    ///     AlbumData4
    /// </summary>
    /// <typeparam name="T"></typeparam>
    public partial class AlbumData4Decorator<T> : Decorator<T>
    {
        partial void doAddOtherConfig();
        /// <summary>
        ///     
        /// </summary>
        /// <typeparam name="result"></typeparam>
        public AlbumData4Decorator(Result<T> result)
            : base(result)
        {

        }
        /// <summary>
        ///     
        /// </summary>
        /// <typeparam name="result"></typeparam>
        public override void doAddConfig()
        {
            base.doAddConfig();
            this.Config.MapType<AlbumData>(map => map
                
                    .Field<System.Int64>(field => field.AlbumID, type => type.To("id"))

                    .Field<System.Int64>(field => field.CategoryID, type => type.To("category_id"))

                    .Field<System.String>(field => field.CoverPath, type => type.To("cover_path"))

                    .Field<System.Int64>(field => field.CreateDate, type => type.To("created_at"))

                    .Field<System.String>(field => field.Intro, type => type.To("intro"))

                    .Field<System.Boolean>(field => field.IsVerified, type => type.To("is_v"))

                    .Field<System.String>(field => field.NickName, type => type.To("nickname"))

                    .Field<System.String>(field => field.Title, type => type.To("title"))

                    .Field<System.Int32>(field => field.TrackCount, type => type.To("tracks"))

                    .Field<System.Int64>(field => field.Uid, type => type.To("uid"))

                    .Field<System.Int64>(field => field.UpdateDate, type => type.To("updated_at"))

            );
            this.doAddOtherConfig();
        }
    }
}
