
// <auto-generated>
//     此代码由工具生成。
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
//		如存在本生成代码外的新需求，请在相同命名空间下创建同名分部类实现 CategoryDataConfigurationAppend 分部方法。
// </auto-generated>
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

using FluentJson.Configuration;
using FluentJson;
using XIMALAYACOPY.Core.Data.Decorator;
using XIMALAYACOPY.Core.Models.Category;

namespace XIMALAYACOPY.Core.Data
{
    /// <summary>
    ///     CategoryData
    /// </summary>
    /// <typeparam name="T"></typeparam>
    public partial class CategoryDataDecorator<T> : Decorator<T>
    {
        partial void doAddOtherConfig();
        /// <summary>
        ///     
        /// </summary>
        /// <typeparam name="result"></typeparam>
        public CategoryDataDecorator(Result<T> result)
            : base(result)
        {

        }
        /// <summary>
        ///     
        /// </summary>
        /// <typeparam name="result"></typeparam>
        public override void doAddConfig()
        {
            base.doAddConfig();
            this.Config.MapType<CategoryData>(map => map
                
                    .Field<System.Int32>(field => field.ID, type => type.To("id"))

                    .Field<System.String>(field => field.Title, type => type.To("title"))

                    .Field<System.String>(field => field.CoverPath, type => type.To("coverPath"))

                    .Field<System.Boolean>(field => field.IsChecked, type => type.To("isChecked"))

                    .Field<System.Int32>(field => field.OrderNum, type => type.To("orderNum"))

                    .Field<System.String>(field => field.Name, type => type.To("name"))

                    .Field<XIMALAYACOPY.Core.Models.Sound.SoundData[]>(field => field.Sounds, type => type.To("sounds"))

            );
            this.doAddOtherConfig();
        }
    }
}
