
// <auto-generated>
//     此代码由工具生成。
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
//		如存在本生成代码外的新需求，请在相同命名空间下创建同名分部类实现 SoundData4ConfigurationAppend 分部方法。
// </auto-generated>
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

using FluentJson.Configuration;
using FluentJson;
using XIMALAYACOPY.Core.Data.Decorator;
using XIMALAYACOPY.Core.Models.Sound;

namespace XIMALAYACOPY.Core.Data
{
    /// <summary>
    ///     SoundData4
    /// </summary>
    /// <typeparam name="T"></typeparam>
    public partial class SoundData4Decorator<T> : Decorator<T>
    {
        partial void doAddOtherConfig();
        /// <summary>
        ///     
        /// </summary>
        /// <typeparam name="result"></typeparam>
        public SoundData4Decorator(Result<T> result)
            : base(result)
        {

        }
        /// <summary>
        ///     
        /// </summary>
        /// <typeparam name="result"></typeparam>
        public override void doAddConfig()
        {
            base.doAddConfig();
            this.Config.MapType<SoundData>(map => map
                
                    .Field<System.Int64>(field => field.TrackId, type => type.To("id"))

                    .Field<System.Int64>(field => field.AlbumID, type => type.To("album_id"))

                    .Field<System.String>(field => field.AlbumTitle, type => type.To("album_title"))

                    .Field<System.Int64>(field => field.CommentCount, type => type.To("count_comment"))

                    .Field<System.Int64>(field => field.CreateAt, type => type.To("created_at"))

                    .Field<System.Double>(field => field.Duration, type => type.To("duration"))

                    .Field<System.Boolean>(field => field.IsLike, type => type.To("is_like"))

                    .Field<System.Boolean>(field => field.IsRelay, type => type.To("iRelay"))

                    .Field<System.Int64>(field => field.LikeCount, type => type.To("count_like"))

                    .Field<System.String>(field => field.PlayUrl32, type => type.To("play_path_32"))

                    .Field<System.Int64>(field => field.PlayCount, type => type.To("count_play"))

                    .Field<System.Int64>(field => field.ShareCount, type => type.To("count_share"))

                    .Field<System.String>(field => field.Title, type => type.To("title"))

                    .Field<System.Int32>(field => field.UploadSource, type => type.To("uploadSource"))

                    .Field<System.Int32>(field => field.OpType, type => type.To("userSource"))

                    .Field<System.String>(field => field.WaveForm, type => type.To("waveform"))

                    .Field<System.Int32>(field => field.ActivityId, type => type.To("activity_id"))

                    .Field<System.String>(field => field.AlbumImage86, type => type.To("album_cover_path"))

                    .Field<System.Int64>(field => field.CategoryID, type => type.To("category_id"))

                    .Field<System.String>(field => field.CoverSmall, type => type.To("cover_path"))

                    .Field<System.Boolean>(field => field.IsVerified, type => type.To("is_v"))

                    .Field<System.String>(field => field.NickName, type => type.To("nickname"))

                    .Field<System.String>(field => field.PlayUrl64, type => type.To("play_path_64"))

                    .Field<System.Int64>(field => field.UID, type => type.To("uid"))

                    .Field<System.Int64>(field => field.UpdateAt, type => type.To("updated_at"))

            );
            this.doAddOtherConfig();
        }
    }
}
